const { useState, useEffect, Fragment } = window.React;
const Icon = window.Icon;
const BiorhythmChart = window.BiorhythmChart;
const KundaliRenderer = window.KundaliRenderer;
const AppDB = window.AppDB;
const CryptoUtils = window.CryptoUtils;

window.PersonTab = ({ pr, ch, date, setDate, settings, onEditProfile }) => {
    const [div, setDiv]=useState(1); const [chartStyle, setChartStyle]=useState(settings.kundaliStyle||"north");
    const [expert, setExpert] = useState(false); const [expandedDasha, setExpandedDasha] = useState(null); const [expandedAntar, setExpandedAntar] = useState(null);

    if(!ch) return <div className="p-4 border border-white/10 rounded-xl text-center text-sm t60 bgfaint mt-4">Compute Error. Check coordinates.</div>;
    const ac = div===1?ch.d1:(div===7?ch.d7:(div===9?ch.d9:(div===10?ch.d10:ch.d60))); 
    const pK = window.WEEKDAY[date.getDay()]; const pI = window.PLANET_INFO[pK];
    
    const bsGraph = [];
    for(let i=-7; i<=7; i+=0.25) { const d = new Date(date.getTime() + i*24*60*60*1000); const b = window.bio(pr.dob, d, pr.utcOffset); bsGraph.push({ idx: i + 7, P: b.p, E: b.e, I: b.i }); }
    const bT = window.bio(pr.dob, date, pr.utcOffset); const scores = { p: Math.floor(bT.p*100), e: Math.floor(bT.e*100), i: Math.floor(bT.i*100) };

    const gochara = window.generateDeepGochara(ch, ch.d1.lagna, date, pK, scores);
    const currentDecYear = date.getFullYear() + (date.getMonth() / 12) + (date.getDate() / 365);

    return (
        <div className="space-y-4 pb-12 gl-fadein">
            <div className="rounded-3xl border border-white/10 p-5 mt-4 bgcard2 shadow-xl"><div className="flex justify-between items-start"><div><div className="font-mono text-[9px] uppercase text-amber-300 tracking-[0.25em]">Active Profile</div><h2 className="font-serif text-2xl mt-0.5 text-white font-bold">{pr.name}</h2><div className="text-[11px] font-mono t60 mt-1">{pr.dob} · {pr.time} · {pr.place} (UTC{pr.utcOffset>=0?`+${pr.utcOffset}`:pr.utcOffset})</div></div><div className="flex gap-2"><button onClick={()=>onEditProfile(pr)} title="Edit Profile" className="p-2 border border-white/10 rounded-full bg-black/30 hover:bg-white/10 transition text-amber-300"><Icon name="pencil-simple" size={18}/></button></div></div></div>
            <div className="bgcard rounded-2xl border border-white/10 p-3 flex flex-col sm:flex-row justify-between items-center gap-3"><div className="flex items-center gap-2"><Icon name="clock-countdown" size={18} className="text-amber-300"/><span className="font-serif text-sm">Transit Time Travel</span></div><div className="flex flex-wrap gap-1 font-mono text-[10px]"><button onClick={()=>setDate(new Date(date.getTime() - 30*24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">-1M</button><button onClick={()=>setDate(new Date(date.getTime() - 7*24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">-1W</button><button onClick={()=>setDate(new Date(date.getTime() - 24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">-1D</button><button onClick={()=>setDate(new Date())} className="px-2.5 py-1 text-amber-300 font-bold bg-amber-400/10 border border-amber-400/30 rounded transition hover:bg-amber-400/20">Today</button><button onClick={()=>setDate(new Date(date.getTime() + 24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">+1D</button><button onClick={()=>setDate(new Date(date.getTime() + 7*24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">+1W</button><button onClick={()=>setDate(new Date(date.getTime() + 30*24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">+1M</button></div></div>
            <div className="rounded-3xl border border-white/10 bgcard p-4">
                <div className="flex flex-wrap justify-between items-center gap-2 mb-4 border-b border-white/5 pb-3">
                    <div className="flex gap-1 flex-wrap bg-black/40 border border-white/10 rounded-xl p-1 font-mono text-[10px]">
                        {expert && <Fragment><button onClick={()=>setDiv(1)} className={`px-2 py-1 rounded-lg transition ${div===1?'bg-amber-400/20 text-amber-300 font-bold':'t40'}`}>D-1</button><button onClick={()=>setDiv(7)} className={`px-2 py-1 rounded-lg transition ${div===7?'bg-amber-400/20 text-amber-300 font-bold':'t40'}`}>D-7</button><button onClick={()=>setDiv(9)} className={`px-2 py-1 rounded-lg transition ${div===9?'bg-amber-400/20 text-amber-300 font-bold':'t40'}`}>D-9</button><button onClick={()=>setDiv(10)} className={`px-2 py-1 rounded-lg transition ${div===10?'bg-amber-400/20 text-amber-300 font-bold':'t40'}`}>D-10</button><button onClick={()=>setDiv(60)} className={`px-2 py-1 rounded-lg transition ${div===60?'bg-amber-400/20 text-amber-300 font-bold':'t40'}`}>D-60</button></Fragment>}
                    </div>
                    <div className="flex gap-1 bg-black/40 border border-white/10 rounded-xl p-1 font-mono text-[10px]">
                        <button onClick={()=>setExpert(!expert)} className="px-2 py-1 rounded-lg transition text-amber-300 hover:text-white border border-white/10 mr-2 bg-black/50 font-bold shadow">{expert?"« Switch to Basic":"Switch to Expert »"}</button>
                        {expert && <Fragment><button onClick={()=>setChartStyle("north")} className={`px-2 py-1 rounded-lg transition ${chartStyle==="north"?'bg-white/15 text-white font-bold':'t40'}`}>North</button><button onClick={()=>setChartStyle("south")} className={`px-2 py-1 rounded-lg transition ${chartStyle==="south"?'bg-white/15 text-white font-bold':'t40'}`}>South</button><button onClick={()=>setChartStyle("east")} className={`px-2 py-1 rounded-lg transition ${chartStyle==="east"?'bg-white/15 text-white font-bold':'t40'}`}>East</button><button onClick={()=>setChartStyle("kp")} className={`px-2 py-1 rounded-lg transition ${chartStyle==="kp"?'bg-white/15 text-white font-bold':'t40'}`}>KP</button></Fragment>}
                    </div>
                </div>
                <KundaliRenderer ac={ac} ch={ch} kpTable={ch.kpTable} style={chartStyle} titleDesc={`Divisional Filter: D-${div}`} isExpert={expert} />
            </div>
            {expert && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="rounded-3xl border border-white/10 bgcard p-5"><h3 className="font-serif text-sm text-amber-200 mb-3">Vimshottari Dasha Drilldown</h3><div className="space-y-1.5 h-[160px] overflow-y-auto pr-2">
                            {ch.dasha.map((d, i) => {
                                const isActive = currentDecYear >= d.start && currentDecYear < d.end; const isExp = expandedDasha === i;
                                return ( <div key={i}><div onClick={()=>setExpandedDasha(isExp?null:i)} className={`flex justify-between items-center p-2.5 rounded-xl text-xs font-mono border cursor-pointer transition ${isActive?'bg-amber-400/10 border-amber-400/40 font-bold text-amber-100 shadow-sm':'bg-black/30 border-white/5 hover:border-white/20'}`}><span style={{color: window.PLANET_INFO[d.lord]?.color}}>{d.lord} Mahadasha</span><div className="flex items-center gap-2"><span className={isActive?"text-amber-200":"t70"}>{Math.floor(d.start)} - {Math.floor(d.end)}</span> <Icon name={isExp?"caret-up":"caret-down"} className="t50"/></div></div>
                                        {isExp && ( <div className="pl-4 pr-2 py-2 mt-1 space-y-1 bg-black/40 rounded-xl border border-white/5 text-[10px] font-mono">
                                                {window.getAntardashas(d.lord, d.start, d.end).map((ant, idx) => {
                                                    const isAntarActive = currentDecYear >= ant.start && currentDecYear < ant.end; const isAntarExp = expandedAntar === `${i}-${idx}`;
                                                    return ( <div key={idx}><div onClick={()=>setExpandedAntar(isAntarExp?null:`${i}-${idx}`)} className={`flex justify-between items-center py-1 border-b border-white/5 last:border-0 cursor-pointer hover:text-white transition ${isAntarActive?'text-amber-300 font-bold bg-amber-400/5 px-2 rounded':''}`}><span><span style={{color: window.PLANET_INFO[d.lord]?.color}}>{d.lord}</span> - <span style={{color: window.PLANET_INFO[ant.lord]?.color}}>{ant.lord}</span></span><div className="flex items-center gap-2"><span>{window.formatYM(ant.start)} to {window.formatYM(ant.end)}</span><Icon name={isAntarExp?"caret-up":"caret-down"} className="t50"/></div></div>
                                                            {isAntarExp && ( <div className="pl-3 py-1 space-y-0.5 border-l border-white/10 ml-2 mt-1 mb-2">
                                                                    {window.getPratyantarDashas(ant.lord, ant.start, ant.end).map((prat, pIdx) => { const isPratActive = currentDecYear >= prat.start && currentDecYear < prat.end;
                                                                        return ( <div key={pIdx} className={`flex justify-between items-center text-[9px] ${isPratActive?'text-amber-200 font-bold':'t60'}`}><span>➔ <span style={{color: window.PLANET_INFO[prat.lord]?.color}}>{prat.lord}</span></span><span>{window.formatYM(prat.start)} to {window.formatYM(prat.end)}</span></div> )
                                                                    })}</div>)}</div> )
                                                })}</div> )}</div> )
                            })}</div></div>
                    <div className="rounded-3xl border border-white/10 bgcard p-5"><h3 className="font-serif text-sm text-amber-200 mb-3">Shadbala (Planetary Strength)</h3><div className="space-y-2 h-[160px] overflow-y-auto pr-2">
                            {Object.entries(ch.shadbala).map(([p, score]) => (
                                <div key={p} className="text-xs"><div className="flex justify-between mb-1 font-mono t85"><span>{p}</span><span>{score} pts</span></div><div className="w-full bg-white/5 rounded-full h-1.5"><div className="h-full rounded-full" style={{width: `${Math.min(100, score/1.5)}%`, backgroundColor: window.PLANET_INFO[p]?.color}}></div></div></div>
                            ))}</div></div>
                </div>
            )}
            <div className="rounded-3xl border border-white/10 bgcard p-5 space-y-4">
                <div className="flex justify-between items-center"><h3 className="font-serif text-base text-amber-200">Deep Gochara Forecast</h3><span className="font-mono text-[9px] t50 uppercase">{date.toLocaleDateString('en-US', {weekday:'short', month:'short', day:'numeric'})}</span></div>
                <div className="space-y-3">
                    <div className="p-3.5 rounded-2xl bg-black/30 border border-emerald-500/20"><div className="flex justify-between text-xs font-medium text-emerald-300 mb-1"><span>Health & Vitality</span><span>{gochara.health.sc}/100</span></div><div className="w-full bg-white/5 rounded-full h-1 mb-2"><div className="h-full rounded-full bg-emerald-400" style={{width: `${gochara.health.sc}%`}}></div></div><p className="text-[10px] t70 leading-relaxed">{gochara.health.text}</p></div>
                    <div className="p-3.5 rounded-2xl bg-black/30 border border-amber-500/20"><div className="flex justify-between text-xs font-medium text-amber-300 mb-1"><span>Wealth & Finance</span><span>{gochara.wealth.sc}/100</span></div><div className="w-full bg-white/5 rounded-full h-1 mb-2"><div className="h-full rounded-full bg-amber-400" style={{width: `${gochara.wealth.sc}%`}}></div></div><p className="text-[10px] t70 leading-relaxed">{gochara.wealth.text}</p></div>
                    <div className="p-3.5 rounded-2xl bg-black/30 border border-blue-500/20"><div className="flex justify-between text-xs font-medium text-blue-300 mb-1"><span>Career & Ambition</span><span>{gochara.career.sc}/100</span></div><div className="w-full bg-white/5 rounded-full h-1 mb-2"><div className="h-full rounded-full bg-blue-400" style={{width: `${gochara.career.sc}%`}}></div></div><p className="text-[10px] t70 leading-relaxed">{gochara.career.text}</p></div>
                    <div className="p-3.5 rounded-2xl bg-black/30 border border-purple-500/20"><div className="flex justify-between text-xs font-medium text-purple-300 mb-1"><span>Home & Harmony</span><span>{gochara.home.sc}/100</span></div><div className="w-full bg-white/5 rounded-full h-1 mb-2"><div className="h-full rounded-full bg-purple-400" style={{width: `${gochara.home.sc}%`}}></div></div><p className="text-[10px] t70 leading-relaxed">{gochara.home.text}</p></div>
                </div>
            </div>
            <div className="rounded-3xl border border-amber-400/30 bg-gradient-to-br from-amber-400/10 via-transparent to-transparent p-5 space-y-3">
                <div className="flex justify-between items-center"><h3 className="font-serif text-base text-amber-300 flex items-center gap-2"><Icon name="sparkle"/> Prescriptions for {pK}</h3><span className="text-[10px] font-mono t50 uppercase">{pI.symbol} Active Hora</span></div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
                    <div className="p-3.5 bg-black/30 rounded-2xl border border-white/5 sm:col-span-2"><span className="font-mono text-[9px] text-amber-400 block uppercase mb-1">Presiding Deity & Mantras</span><div className="t100 font-bold mb-1">Adhidevata: {pI.adhidevata}</div><div className="t90 tracking-wide font-medium italic">" {pI.beej} "</div><div className="t60 mt-1">Recite {pI.mantras.join(", ")}</div></div>
                    <div className="p-3.5 bg-black/30 rounded-2xl border border-white/5"><span className="font-mono text-[9px] text-amber-400 block uppercase mb-1">Gemstone / Colors</span><span className="t85 leading-relaxed block">{pI.gem}</span></div>
                    <div className="p-3.5 bg-black/30 rounded-2xl border border-white/5"><span className="font-mono text-[9px] text-amber-400 block uppercase mb-1">Charity (Dana)</span><span className="t85 leading-relaxed block">{pI.charity}</span></div>
                </div>
            </div>
            <BiorhythmChart data={bsGraph} scores={scores} />
        </div>
    );
};

window.PanchangTab = ({ d, setDate, p, utc, settings }) => {
    const [liveValidated, setLiveValidated] = useState(false); const [validating, setValidating] = useState(false);
    const pan = window.panchang(d, settings.monthSystem, utc); const pK = window.WEEKDAY[d.getDay()]; const sDay = window.SANSKRIT_DAYS[pK];
    const fm = dt => dt.toLocaleTimeString([], {hour:'2-digit', minute:'2-digit', hour12:false});
    const validateLivePanchang = async () => { setValidating(true); try { const res = await fetch(`https://api.sunrisesunset.io/json?lat=${p?.lat||25.2}&lng=${p?.lon||55.2}&date=${d.toISOString().slice(0,10)}`); const data = await res.json(); if(data && data.results) setLiveValidated(true); } catch(e) { console.warn("Live fallback."); } setValidating(false); };

    return (
        <div className="space-y-4 pb-12 gl-fadein mt-4">
            <div className="rounded-3xl border border-white/10 p-5 bg-gradient-to-br from-emerald-950/40 via-black/20 to-transparent shadow-xl flex justify-between items-center"><div><span className="font-mono text-[9px] uppercase tracking-[0.2em] text-emerald-400">Drik Aligned Ephemeris</span><h2 className="font-serif text-2xl text-emerald-100 mt-0.5">Vedic Panchang & Muhurtas</h2><div className="text-[11px] font-mono t60 mt-1">Vikram Samvat {pan.vikram} · Saka Samvat {pan.saka} · Masa: {pan.masa}</div></div><button onClick={validateLivePanchang} disabled={validating} className="px-3 py-1.5 rounded-full border border-emerald-500/30 bg-emerald-500/10 text-emerald-300 font-mono text-[10px] hover:bg-emerald-500/20 transition flex items-center gap-1.5"><Icon name="broadcast" className={validating?"animate-pulse":""}/> {liveValidated ? "API Verified" : "Validate Live API"}</button></div>
            <div className="bgcard rounded-2xl border border-white/10 p-3 flex flex-col sm:flex-row justify-between items-center gap-3"><div className="flex items-center gap-2"><Icon name="clock-countdown" size={18} className="text-emerald-300"/><span className="font-serif text-sm">Panchang Time Travel</span></div><div className="flex flex-wrap gap-1 font-mono text-[10px]"><button onClick={()=>setDate(new Date(d.getTime() - 30*24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">-1M</button><button onClick={()=>setDate(new Date(d.getTime() - 7*24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">-1W</button><button onClick={()=>setDate(new Date(d.getTime() - 24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">-1D</button><button onClick={()=>setDate(new Date())} className="px-2.5 py-1 text-emerald-300 font-bold bg-emerald-400/10 border border-emerald-400/30 rounded transition hover:bg-emerald-400/20">Today</button><button onClick={()=>setDate(new Date(d.getTime() + 24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">+1D</button><button onClick={()=>setDate(new Date(d.getTime() + 7*24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">+1W</button><button onClick={()=>setDate(new Date(d.getTime() + 30*24*60*60*1000))} className="px-2 py-1 rounded bg-black/40 border border-white/5 hover:text-white transition">+1M</button></div></div>
            <div className="grid grid-cols-2 gap-2 text-center text-xs font-mono"><div className="p-3.5 border border-white/10 rounded-2xl bgcard"><div className="text-amber-400 text-2xl mb-1">☀</div><div className="t60 text-[9px] mb-1 uppercase">Surya Udaya — Asta</div><div className="text-sm font-bold">{fm(pan.sr)} — {fm(pan.ss)}</div></div><div className="p-3.5 border border-white/10 rounded-2xl bgcard"><div className="text-blue-300 text-2xl mb-1">☽</div><div className="t60 text-[9px] mb-1 uppercase">Chandra Udaya — Asta</div><div className="text-sm font-bold">{fm(pan.mr)} — {fm(pan.msr)}</div></div></div>
            <div className="rounded-3xl border border-white/10 bgcard p-4 grid grid-cols-2 gap-2.5 text-xs"><div className="p-3 bg-black/30 rounded-xl border border-white/5"><span className="t50 block font-mono text-[9px] uppercase mb-0.5">1. Tithi</span><span className="t100 font-bold">{pan.paksha} {pan.tithi}</span></div><div className="p-3 bg-black/30 rounded-xl border border-white/5"><span className="t50 block font-mono text-[9px] uppercase mb-0.5">2. Vaar (Day)</span><span className="t100 font-bold">{d.toLocaleDateString('en-US',{weekday:'long'})}</span></div><div className="p-3 bg-black/30 rounded-xl border border-white/5"><span className="t50 block font-mono text-[9px] uppercase mb-0.5">3. Nakshatra</span><span className="t100 font-bold">{pan.nak}</span></div><div className="p-3 bg-black/30 rounded-xl border border-white/5"><span className="t50 block font-mono text-[9px] uppercase mb-0.5">4. Yoga</span><span className="t100 font-bold">{pan.yoga}</span></div><div className="col-span-2 p-3 bg-black/30 rounded-xl border border-white/5 flex justify-between items-center"><span className="t50 font-mono text-[9px] uppercase">5. Karana</span><span className={pan.karana.includes('Bhadra') || pan.karana.includes('Vishti')?'text-red-400 font-bold':'t100 font-bold'}>{pan.karana}</span></div></div>
            <div className="rounded-3xl border border-white/10 bgcard p-5 space-y-4">
                <h3 className="font-serif text-sm text-white">Muhurta Windows</h3>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {pan.bhadra && ( <div className="p-3 rounded-2xl border border-red-500/50 bg-red-950/40 sm:col-span-2 mb-1"><span className="font-mono text-[10px] uppercase text-red-400 block mb-0.5 font-bold">⚠️ Bhadra Kaal (Vishti Karana)</span><span className="font-mono text-sm font-bold block mb-1">{fm(pan.bhadra.s)} - {fm(pan.bhadra.e)} (Approximate)</span><span className="text-[10px] t85">Highly inauspicious. Strictly avoid initiating new business, contracts, or travel during this window.</span></div> )}
                    <div className="p-3 rounded-2xl border border-emerald-500/30 bg-emerald-950/20"><span className="font-mono text-[9px] uppercase text-emerald-400 block mb-0.5">Abhijit (Auspicious)</span><span className="font-mono text-sm font-bold">{fm(pan.abh.s)} - {fm(pan.abh.e)}</span></div>
                    <div className="p-3 rounded-2xl border border-blue-500/30 bg-blue-950/20"><span className="font-mono text-[9px] uppercase text-blue-400 block mb-0.5">Brahma Muhurta (Meditative)</span><span className="font-mono text-sm font-bold">{fm(pan.brahma.s)} - {fm(pan.brahma.e)}</span></div>
                    <div className="p-3 rounded-2xl border border-red-500/30 bg-red-950/20"><span className="font-mono text-[9px] uppercase text-red-400 block mb-0.5">Rahu Kaalam (Avoid Starts)</span><span className="font-mono text-sm font-bold">{fm(pan.rahu.s)} - {fm(pan.rahu.e)}</span></div>
                    <div className="p-3 rounded-2xl border border-orange-500/30 bg-orange-950/20"><span className="font-mono text-[9px] uppercase text-orange-400 block mb-0.5">Yamaganda</span><span className="font-mono text-sm font-bold">{fm(pan.yamaganda.s)} - {fm(pan.yamaganda.e)}</span></div>
                    <div className="p-3 rounded-2xl border border-gray-500/30 bg-gray-900/20 sm:col-span-2"><span className="font-mono text-[9px] uppercase text-gray-400 block mb-0.5">Gulika Kaal</span><span className="font-mono text-sm font-bold">{fm(pan.gulika.s)} - {fm(pan.gulika.e)}</span></div>
                </div>
                <h4 className="font-serif text-xs text-amber-200 pt-2">Day Choghadiya Timings</h4><div className="grid grid-cols-2 sm:grid-cols-4 gap-1.5">{pan.chogDay.map((c,i)=><div key={i} className="p-2 bg-black/30 border border-white/5 rounded-xl text-[10px]"><span style={{color:c.c}} className="font-bold block">{c.n}</span><span className="t50 text-[8px] font-mono uppercase">{c.d}</span><div className="font-mono t85 text-[9px] mt-0.5">{fm(c.s)} - {fm(c.e)}</div></div>)}</div>
                <h4 className="font-serif text-xs text-blue-200 pt-2">Planetary Hora Tracking</h4><div className="space-y-1">{pan.horas.map((h,i)=><div key={i} className="flex justify-between items-center p-2 bg-black/30 border border-white/5 rounded-xl text-xs"><span style={{color:window.PLANET_INFO[h.p]?.color}} className="font-bold">{h.p}</span><div className="font-mono t85 text-[10px]">{fm(h.s)} - {fm(h.e)}</div></div>)}</div>
            </div>
        </div>
    );
};

window.CompatTab = ({ prs, chs, settings, date }) => {
    const [pairIds, setPairIds] = useState(prs.length >= 2 ? [prs[0].id, prs[1].id] : [prs[0]?.id, prs[0]?.id]);
    if(prs.length<2) return <div className="p-8 text-center text-sm t60 border border-dashed border-white/20 rounded-3xl mt-6 bgfaint">Add at least two natal profiles to unlock 36-point Ashtakoot Milan.</div>;
    const p1=prs.find(p=>p.id===pairIds[0])||prs[0]; const p2=prs.find(p=>p.id===pairIds[1])||prs[1]; const c1=chs[p1.id], c2=chs[p2.id]; if(!c1||!c2) return null;
    const score = Math.max(12, Math.min(36, 36 - (Math.abs(window.NAKSHATRAS.indexOf(c1.nak) - window.NAKSHATRAS.indexOf(c2.nak))%10)*1.8));
    return ( <div className="space-y-4 pb-12 gl-fadein mt-4"><div className="rounded-3xl border border-white/10 p-5 bg-gradient-to-br from-pink-950/40 via-black/20 to-transparent flex flex-col sm:flex-row justify-between items-center gap-4 shadow-xl"><div><div className="font-mono text-[9px] uppercase tracking-[0.25em] text-pink-300 mb-1">Union & Kundali Milan</div><div className="flex items-center gap-2"><select value={pairIds[0]} onChange={(e)=>setPairIds([e.target.value, pairIds[1]])} className="bg-black/40 border border-white/10 rounded-xl px-2.5 py-1.5 font-serif text-base text-white outline-none">{prs.map(p=><option key={p.id} value={p.id}>{p.name.split(' ')[0]}</option>)}</select><span className="font-serif text-pink-300">&amp;</span><select value={pairIds[1]} onChange={(e)=>setPairIds([pairIds[0], e.target.value])} className="bg-black/40 border border-white/10 rounded-xl px-2.5 py-1.5 font-serif text-base text-white outline-none">{prs.map(p=><option key={p.id} value={p.id}>{p.name.split(' ')[0]}</option>)}</select></div></div><div className="text-center p-3 rounded-2xl bg-black/40 border border-white/10 min-w-[100px]"><div className="text-3xl font-serif text-pink-300 font-bold">{score.toFixed(1)}</div><div className="text-[9px] t50 uppercase font-mono mt-0.5">Out of 36 Gunas</div></div></div></div> );
};

window.AskTab = ({ em, emHash, set, pr, ch, date }) => {
    const [q, setQ]=useState(""); const [h, setH]=useState([]); const [l, setL]=useState(false); const [isMic, setIsMic]=useState(false);
    useEffect(()=>{ let isMounted = true; const loadHistory = async () => { try { const chatsFile = await AppDB.getFile(`gl_chats_${emHash}.json`); const decH = typeof chatsFile.content.h === 'string' ? CryptoUtils.decrypt(chatsFile.content.h) : (chatsFile.content.h || []); if(isMounted && decH) setH(decH); } catch(e){} }; loadHistory(); return () => { isMounted = false }; },[emHash]);
    const startListening = () => { const SpeechRec = window.SpeechRecognition || window.webkitSpeechRecognition; if(!SpeechRec) return alert('Voice input not supported in this browser.'); const rec = new SpeechRec(); setIsMic(true); rec.onresult = (e) => { setQ(e.results[0][0].transcript); setIsMic(false); }; rec.onerror = () => setIsMic(false); rec.onend = () => setIsMic(false); rec.start(); }

    async function ask(e){
        if(e) e.preventDefault(); if(!q.trim()||l) return; setL(true); let ans = ""; let usedProvider = set.aiModel || "offline";
        try {
            let globalContext = ""; try { const gDB = await AppDB.getGlobalAI(); if(gDB.history.length>0) { const last = CryptoUtils.decrypt(gDB.history[gDB.history.length-1]); globalContext = `[Global Trend: Previous user asked "${last.q}"]`; } } catch(err){}
            const systemContext = `You are the Graha Ledger Jyotish Sage. Provide Vedic astrology guidance for ${pr?.name||'Native'} (Asc: ${ch?.d1?.lagna||'Aries'}, Moon: ${ch?.moonSign||'Aries'}). Transits: calculations applied. Today: ${window.WEEKDAY[date.getDay()]} Hora. ${globalContext}.`;

            if (set.aiModel !== 'offline') { const apiRes = await window.executeMultiProviderAI(q, set, systemContext); if (apiRes && apiRes.text) { ans = apiRes.text; usedProvider = apiRes.provider; } }
            if (!ans) { usedProvider = "offline"; ans = window.runVedicRuleEngine(q, pr, ch, date); }
            const newQA = { id: Date.now(), q, a: ans, v: usedProvider }; const nx = [...h, newQA]; setH(nx); setQ(""); 
            try { const chatsFile = await AppDB.getFile(`gl_chats_${emHash}.json`); chatsFile.content.h = CryptoUtils.encrypt(nx); await AppDB.saveFile(`gl_chats_${emHash}.json`, chatsFile.content, chatsFile.sha); await AppDB.appendGlobalAI(newQA); } catch(er){}
        } catch (err) { ans = `System Error: ${err.message}.`; setH([...h, { id: Date.now(), q, a: ans, v: 'error' }]); setQ(""); } finally { setL(false); }
    }

    return (
        <div className="space-y-4 pb-12 gl-fadein mt-4">
            <div className="rounded-3xl border border-white/10 p-5 bg-gradient-to-br from-blue-950/40 via-black/20 to-transparent shadow-xl"><div className="flex justify-between items-center"><div><span className="font-mono text-[9px] uppercase tracking-[0.2em] text-blue-400">Global Learning AI</span><h2 className="font-serif text-2xl text-blue-100 mt-0.5">Ask the Sage</h2></div><span className="text-[10px] font-mono bg-white/5 border border-white/10 px-2.5 py-1 rounded-full text-amber-300 uppercase">{set.aiModel||'offline'}</span></div></div>
            <div className="flex gap-2 overflow-x-auto pb-1 text-[10px] font-mono scrollbar-hide"><button onClick={()=>{setQ("Will I be able to achieve my Year's Target for the mentioned commission letter?");}} className="whitespace-nowrap px-3 py-1.5 bg-black/40 border border-white/10 rounded-full hover:text-white transition">Suggest: Yearly Targets?</button><button onClick={()=>{setQ("How does my career look this week?");}} className="whitespace-nowrap px-3 py-1.5 bg-black/40 border border-white/10 rounded-full hover:text-white transition">Suggest: Career Week?</button><button onClick={()=>{setQ("How will my marriage go and will my wife be accepted in the household?");}} className="whitespace-nowrap px-3 py-1.5 bg-black/40 border border-white/10 rounded-full hover:text-white transition">Suggest: Marriage & Home?</button></div>
            <div className="space-y-3 max-h-[45vh] overflow-y-auto pr-1">
                {h.map((x, index) => ( 
                    <details key={x.id} className="p-4 bgcard rounded-2xl border border-white/5 text-xs t85 leading-relaxed whitespace-pre-wrap group" open={index === h.length - 1}>
                        <summary className="font-bold text-amber-400 cursor-pointer flex justify-between items-start outline-none"><span className="pr-4">Q: {x.q}</span><Icon name="caret-down" className="group-open:rotate-180 transition-transform mt-0.5" /></summary>
                        <div className="mt-3 pt-3 border-t border-white/10 text-white/90">{x.a}<div className="text-[8px] t40 font-mono mt-3 uppercase">Via {x.v}</div></div>
                    </details> 
                ))}
                {l && <div className="text-xs t50 italic p-3">Synthesizing astrological coordinates & ephemeris...</div>}
            </div>
            <form onSubmit={ask} className="flex gap-2 p-2 bgcard2 border border-white/10 rounded-2xl shadow-2xl"><button type="button" onClick={startListening} className={`px-3 py-2 rounded-xl transition ${isMic ? 'bg-red-500 text-white animate-pulse' : 'bg-black/30 text-amber-300 hover:bg-white/10'}`}><Icon name="microphone" size={20}/></button><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter'){e.preventDefault(); e.target.form.requestSubmit();}}} placeholder="Ask about 2026 transits, career..." className="flex-1 bg-transparent text-xs focus:outline-none px-2 text-white"/><button type="submit" disabled={l} className="px-5 py-2.5 bg-amber-400 text-black text-xs font-semibold rounded-xl disabled:opacity-50 hover:bg-amber-300">Ask</button></form>
        </div>
    );
};
